version: "3.7"

services:
  postgresql:
    container_name: keystore-postgres
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - "POSTGRES_PASSWORD=resource"
      - "POSTGRES_USER=resource"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
