version: "3.7"

services:
  db:
    container_name: keystore-db
    image: postgres
    network_mode: "host"
    volumes:
      - pg_data:/var/lib/postgresql/data
  api:
    container_name: keystore-api
    image: ${DOCKER_IMAGE_URL}
    network_mode: "host"
    restart: always
    env_file: .env

volumes:
  pg_data:
